apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: atharvak2427/wanderlust-backend-2
        env:
        - name: MONGO_URL
          value: mongodb://root:rootpassword@mongodb-service:27017
        ports:
        - name: backend-port
          containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - nodePort: 30002
    port: 5000
    targetPort: 5000